server:
  port: 9999

spring:
  application:
    name: luckySite_gateway
  redis:
      host: 127.0.0.1
      port: 6379
      password: mhb19940803751X
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

#路由规则配置
zuul:
  ignoredServices: "*"
  routes:
    luckySite:
      path: /luckySite/**
    luckySite:
      serviceId: luckySite
    luckySite:
      retryable: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true